{
  "is": "issue",
  "title": "Disruption Detected",
  "body": "\u003cp\u003eOur monitoring probes reported instability in access to public IP addresses carrying application traffic.\u003cbr\u003e\nWe also saw major disruptions in access to the Cloud Protector administration console.\u003c/p\u003e\n\u003cp\u003eTraffic continues to be processed, however, with an average latency of 30s.\u003cbr\u003e\nNo abnormal traffic was observed, and application DDoS attacks were immediately ruled out.\u003c/p\u003e\n\u003cp\u003eWe conclude that the cause is external to our infrastructure. Despite opening an incident with our service provider, we have been unable to obtain any clues as to the cause of the incident.\u003c/p\u003e\n",
  "createdAt": "2024-02-06 16:29:00.346706191 +0100 +0100",
  "lastMod": "2024-02-22 16:43:55 +0100 +0100",
  "permalink": "http://localhost:1313/issues/2024-02-06-16-29/",
  "severity": "disrupted",
  "resolved": true,
  "informational": false,
  "resolvedAt": "2024-02-06T17:34:00.14556055+01:00",
  "affected": ["Runtime (legacy)"],
  "filename": "2024-02-06-16-29.md"
}